### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by oksya8and8** [ovikariy/bewell#2]
I would like to use this app in Japanese.
Can you please support Japanese?
Thank you for developing such a great app.

**Comment by ovikariy** [comment]
Thank you for using BeWell app, I'm glad you like it! 

I would love to add Japanese language. Would you help me review and correct the translations please? I added them in this spreadsheet but I use Google Translate and it's not ideal. Once these are corrected, I can push an update over-the-air right away.

[BeWell Translations Spreadsheet](https://docs.google.com/spreadsheets/d/1sBFX_ndjqlGp2BWtGANaj9HvEiG71_xf/edit?usp=sharing&ouid=108007127278494346408&rtpof=true&sd=true)

Thanks a lot!

**Comment by oksya8and8** [comment]
The translation has been corrected, please check if there are no problems.👍

**Comment by ovikariy** [comment]
Perfect, thank you very much for your help!

I integrated the change and published an update. All you have to do to see the update is restart the app twice (first time it will automatically download the update and second time it will apply it)

Then you can select Japanese language in the Settings.

Let me know how it looks and if something doesn't look right, we can make more changes.

<img src="https://user-images.githubusercontent.com/40619619/134251662-6a0e1d35-aa43-4622-9e3e-23bf3c891f60.jpg" height="400" />

**Comment by oksya8and8** [comment]
The Japanese translations of 3, 14, 101, 156, 166, 167, 211, and 214 have been further revised. 

Thank you!

**Comment by ovikariy** [comment]
Updated and published 👍
